name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: arm64-osx
          - os: windows-latest
            triplet: x64-windows
          - os: windows-latest
            triplet: x86-windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up vcpkg
      uses: johnwason/vcpkg-action@v7
      with:
        triplet: ${{ matrix.triplet }}
        pkgs: openssl gtest
        token: ${{ github.token }}

    - name: Configure the test app
      run: cmake . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DBUILD_TESTING=ON

    - name: Build the test app
      run: cmake --build . --config Release

    - name: Run the test app
      run: |
        ctest --verbose -C Release
